version: '3.8'

services:
  app:
    build: .
    container_name: stress
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stress-db:5432/stresslab
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pass1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      stress-db:
        condition: service_healthy
    restart: unless-stopped

  stress-db:
    image: postgres:16
    container_name: stress-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: stresslab
    ports:
      - "5433:5432" # 로컬에서 사용할 포트
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stresslab"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  jmeter:
    image: justb4/jmeter:5.5
    container_name: stress-jmeter
    volumes:
      - ./jmeter:/jmeter
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true
